# Generated by Django 5.2.4 on 2025-08-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=100),
        ),
    ]
