# Generated by Django 5.2.4 on 2025-08-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=100),
        ),
    ]
