# Generated by Django 5.2.4 on 2025-08-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variations',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
    ]
